language: node_js
node_js:
  - "6"
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - export PORT=8000
  - npm start & sleep 3
  - export NODE_ENV=test
  - export PGDB_TCP_PORT=5432
  - export PGDB_TCP_HOST=127.0.0.1
  - export PGDB_USER=postgres
  - export PGDB_DB=testing
  - psql -c 'create database testing;' -U postgres -w
  - psql -f 'scripttest.sql'
